# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

tracker_type: botsort  # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5  # threshold for the first association based on IoU and ReID detection confidences
track_low_thresh: 0.5  # threshold for the second association based on IoU
new_track_thresh: 0.65  # threshold for init new track if the detection does not match any tracks
track_buffer: 50  # buffer to calculate the time when to remove tracks
match_thresh: 0.9  # threshold for matching tracks
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)
# mot20: False  # for tracker evaluation(not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow  # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5 # used to reject unlikely pairs of tracklets and deetections
appearance_thresh: 0.25 # used to separate positive association of tracklet appearance statse and detections embedding vectors from negative ones
with_reid: False
