# Pipeline configuration file for TurtleTrackingPipeline.py

# video file
video_path_in: /home/serena/Data/Turtles/videos/081217-00020AMsouth.mp4

# output directory
save_dir: /home/serena/Data/Turtles/tracking_out/081217-00020AMsouth

# object detection model
detection_model_path: /home/serena/Data/Turtles/yolov8x_models/train17/weights/best.pt

# classification model
classification_model_path: /home/serena/Data/Turtles/classifier_models/classifier_exp35.pt

# YOLOv5 installation path
YOLOv5_install_path: /home/serena/Data/Turtles/yolov5_turtles

# frame skip
frame_skip: 2

# detection confidence
detection_confidence_threshold: 0.35

# detection iou threshold
detection_iou_threshold: 0.5

# overall classification confidence
overall_class_confidence_threshold: 0.7

# overall class track threshold
overall_class_track_threshold: 0.5

# NOTE:
# tracking parameters are located in install location for Yolov8
# was in /mambaforge/envs/turtles/lib/python3.9/site-packages/ultralytics/tracker/cfg/
# now default to locally-added bottracker/bytetracker config.yamls
