# Pipeline configuration file for TurtleTrackingPipeline.py

# video file
video_path_in: /home/dorian/Code/turtles/turtle_datasets/041219-0569AMsouth.mp4
# output directory
save_dir: /home/dorian/Code/turtles/turtle_datasets/tracking_output


# object detection model
detection_model_path: /home/dorian/Code/turtles/turtle_tracker/weights/20230430_yolov8x_turtlesonly_best.pt

# classification model
classification_model_path: /home/dorian/Code/turtles/turtle_tracker/weights/classifier_exp35.pt

# YOLOv5 installation path
YOLOv5_install_path: /home/dorian/Code/turtles/yolov5_turtles
